Repository samchon/nestia, pull requests merged in 2022-07, with the labels that each got.

#120 Fix #117
  package.json
Labels: bug

#122 Close #121
  demo/array/swagger.json
  demo/simple/swagger.json
  demo/union/swagger.json
  package.json
  src/analyses/ReflectAnalyzer.ts
Labels: enhancement

#125 Fix #123 and Close #124
  .prettierignore
  README.md
  demo/array/src/api/structures/ISaleArticleComment.ts
  demo/array/src/controllers/HealthController.ts
  demo/array/src/controllers/MultipleController.ts
  demo/array/swagger.json
  demo/encrypt/src/api/structures/ISeller.ts
  demo/encrypt/src/controllers/SellerAuthenticateController.ts
  demo/generic/nestia.config.ts
  demo/generic/src/api/functional/consumers/sales/questions/index.ts
  demo/generic/src/api/functional/consumers/sales/reviews/index.ts
  demo/generic/src/api/structures/IAttachmentFile.ts
  demo/generic/src/api/structures/ISaleArticle.ts
  demo/generic/src/api/structures/ISaleInquiry.ts
  demo/generic/src/api/structures/ISaleInquiryAnswer.ts
  demo/generic/src/api/structures/ISaleQuestion.ts
  demo/generic/src/api/structures/ISaleReview.ts
  demo/generic/src/controllers/ConsumerSaleQuestionsController.ts
  demo/generic/src/controllers/ConsumerSaleReviewsController.ts
  demo/generic/src/controllers/SaleInquiriesController.ts
  demo/generic/swagger.json
  demo/recursive/api/structures/ICategory.ts
  demo/recursive/src/controllers/consumer.categories.controller.ts
  demo/simple/.gitignore
  demo/simple/nestia.config.ts
  demo/simple/src/api/functional/consumers/sales/articles/comments/index.ts
  demo/simple/src/api/structures/ISaleArticleComment.ts
  demo/simple/src/controllers/ConsumerSaleArticleCommentsController.ts
  demo/simple/swagger.json
  demo/simple/tsconfig.json
  demo/union/nestia.config.ts
  demo/union/src/api/structures/IAttachmentFile.ts
  demo/union/src/api/structures/IPage.ts
  demo/union/src/api/structures/ISaleArticle.ts
  demo/union/src/api/structures/ISaleEntireArticle.ts
  demo/union/src/api/structures/ISaleInquiry.ts
  demo/union/src/api/structures/ISaleInquiryAnswer.ts
  demo/union/src/api/structures/ISaleQuestion.ts
  demo/union/src/api/structures/ISaleReview.ts
  demo/union/src/controllers/ConsumerSaleEntireArticlesController.ts
  package.json
  src/NestiaApplication.ts
  src/executable/internal/CompilerOptions.ts
  src/utils/ImportDictionary.ts
  tsconfig.json
Labels: bug, enhancement

#132 Fix #126 - Support extended tsconfig.json
  package.json
  src/executable/internal/NestiaCommand.ts
Labels: enhancement

#131 Fix #127 - Error loading nestia.config.ts if compilerOptions.module is changed
  src/executable/internal/NestiaConfig.ts
Labels: enhancement

#130 Fix #129 - Correct typing for compilerOptions
  src/IConfiguration.ts
  src/utils/StripEnums.ts
Labels: enhancement

#138 Fix #137
  demo/generic/src/api/functional/consumers/sales/questions/index.ts
  demo/generic/src/api/functional/consumers/sales/reviews/index.ts
  demo/multiple-paths/src/api/functional/consumers/sales/articles/comments/index.ts
  demo/multiple-paths/src/api/functional/sellers/sales/articles/comments/index.ts
  demo/recursive/src/api/functional/consumers/systematic/categories/index.ts
  demo/safe/src/api/functional/consumers/sales/articles/comments/index.ts
  demo/union/src/api/functional/consumers/sales/entire_articles/index.ts
  package.json
  src/generates/FunctionGenerator.ts
Labels: enhancement
