Repository samchon/nestia, pull requests merged in 2023-08, with the labels that each got.

#493 Upgrade SDK comment tags composer
  packages/sdk/package.json
  packages/sdk/src/generates/SwaggerGenerator.ts
  packages/sdk/src/generates/internal/SdkFunctionProgrammer.ts
  packages/sdk/src/structures/ISwagger.ts
  test/executable/start.js
  test/features/body-manual-assert/swagger.json
  test/features/body-manual-is/swagger.json
  test/features/body-manual-validate/swagger.json
  test/features/body/src/api/functional/body/index.ts
  test/features/body/src/api/functional/health/index.ts
  test/features/body/src/api/functional/performance/index.ts
  test/features/body/src/controllers/HealthController.ts
  test/features/body/src/controllers/PerformanceController.ts
  test/features/body/src/controllers/TypedBodyController.ts
  test/features/body/swagger.json
  test/features/cli-directory/swagger.json
  test/features/cli-pattern/swagger.json
  test/features/config-pattern/swagger.json
  test/features/date/swagger.json
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-assert/swagger.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute-json/swagger.json
  test/features/distribute/swagger.json
  test/features/duplicated/swagger.json
  test/features/e2e/swagger.json
  test/features/encrypted/swagger.json
  test/features/equals/swagger.json
  test/features/exception-filter/swagger.json
  test/features/fastify/swagger.json
  test/features/headers-decompose/swagger.json
  test/features/headers/src/api/functional/headers/index.ts
  test/features/headers/src/controllers/HeadersController.ts
  test/features/headers/swagger.json
  test/features/non-equals/swagger.json
  test/features/param/swagger.json
  test/features/plain/swagger.json
  test/features/query-decompose/swagger.json
  test/features/query/swagger.json
  test/features/route-manual-assert/swagger.json
  test/features/route-manual-is/swagger.json
  test/features/route-manual-stringify/swagger.json
  test/features/route-manual-validate/swagger.json
  test/features/route/swagger.json
  test/features/security/src/api/functional/index.ts
  test/features/security/swagger.json
  test/features/simulate/swagger.json
  test/features/status/swagger.json
  test/features/swagger/swagger.json
  test/features/tags/swagger.json
  test/features/variable/swagger.json
Labels: enhancement

#495 Enhance #473 - support `@TypedHeaders()` in `fetcher` and `sdk`
  packages/core/package.json
  packages/fetcher/package.json
  packages/fetcher/src/Fetcher.ts
  packages/fetcher/src/IConnection.ts
  packages/migrate/package.json
  packages/migrate/src/NestiaMigrateApplication.ts
  packages/sdk/package.json
  packages/sdk/src/analyses/ReflectAnalyzer.ts
  packages/sdk/src/generates/internal/E2eFileProgrammer.ts
  packages/sdk/src/generates/internal/SdkFunctionProgrammer.ts
  packages/sdk/src/generates/internal/SdkSimulationProgrammer.ts
  test/executable/start.js
  test/features/body-manual-assert/src/api/functional/body/index.ts
  test/features/body-manual-is/src/api/functional/body/index.ts
  test/features/body-manual-validate/src/api/functional/body/index.ts
  test/features/body/src/api/functional/body/index.ts
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-assert/packages/api/tsconfig.json
  test/features/distribute-assert/src/api/functional/bbs/articles/index.ts
  test/features/distribute-json/packages/api/package.json
  test/features/distribute-json/src/api/functional/bbs/articles/index.ts
  test/features/distribute/packages/api/package.json
  test/features/distribute/src/api/functional/bbs/articles/index.ts
  test/features/e2e/src/api/functional/bbs/articles/index.ts
  test/features/encrypted/src/api/functional/sellers/authenticate/index.ts
  test/features/encrypted/src/api/functional/sellers/authenticate/password/index.ts
  test/features/encrypted/swagger.json
  test/features/equals/src/api/functional/index.ts
  test/features/exception-filter/src/api/functional/exception/index.ts
  test/features/fastify/src/api/functional/bbs/articles/index.ts
  test/features/fastify/src/api/functional/plain/index.ts
  test/features/fastify/src/api/functional/sellers/authenticate/index.ts
  test/features/fastify/src/api/functional/sellers/authenticate/password/index.ts
  test/features/fastify/swagger.json
  test/features/headers-decompose/nestia.config.ts
  test/features/headers-decompose/src/api/functional/headers/index.ts
  test/features/headers-decompose/src/test/features/api/automated/test_api_headers_emplace.ts
  test/features/headers-decompose/src/test/features/api/automated/test_api_headers_store.ts
  test/features/headers-decompose/src/test/features/api/automated/test_api_headers_update.ts
  test/features/headers-decompose/src/test/features/api/automated/test_api_health_get.ts
  test/features/headers-decompose/src/test/features/api/automated/test_api_performance_get.ts
  test/features/headers-decompose/src/test/features/api/test_api_headers.ts
  test/features/headers/nestia.config.ts
  test/features/headers/src/api/functional/headers/index.ts
  test/features/headers/src/test/features/api/automated/test_api_headers_emplace.ts
  test/features/headers/src/test/features/api/automated/test_api_headers_store.ts
  test/features/headers/src/test/features/api/automated/test_api_headers_update.ts
  test/features/headers/src/test/features/api/automated/test_api_health_get.ts
  test/features/headers/src/test/features/api/automated/test_api_performance_get.ts
  test/features/headers/src/test/features/api/test_api_headers.ts
  test/features/non-equals/src/api/functional/index.ts
  test/features/plain/src/api/functional/plain/index.ts
  test/features/simulate/src/api/functional/bbs/articles/index.ts
  test/features/simulate/src/api/functional/sellers/authenticate/index.ts
  test/features/simulate/src/api/functional/sellers/authenticate/password/index.ts
  test/features/simulate/src/test/features/api/test_api_simulate_invalid_query.ts
  test/features/simulate/swagger.json
  test/package.json
Labels: documentation, enhancement

#498 Enhance #473 - `IConnection.Headerify` to be much stronger
  packages/core/package.json
  packages/core/src/decorators/TypedRoute.ts
  packages/core/src/programmers/TypedHeadersProgrammer.ts
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/fetcher/src/IConnection.ts
  packages/fetcher/src/IEncryptionPassword.ts
  packages/sdk/package.json
  packages/sdk/src/analyses/ReflectAnalyzer.ts
  packages/sdk/src/structures/ISwaggerRoute.ts
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-assert/packages/api/tsconfig.json
  test/features/encrypted/swagger.json
  test/features/fastify/swagger.json
  test/features/headers-decompose/src/api/structures/IHeaders.ts
  test/features/headers-decompose/src/test/features/api/test_api_headers.ts
  test/features/headers-decompose/swagger.json
  test/features/headers/src/api/structures/IHeaders.ts
  test/features/headers/src/test/features/api/test_api_headers.ts
  test/features/headers/swagger.json
  test/features/simulate/swagger.json
  test/features/tags/src/api/functional/bbs/articles/index.ts
  test/features/variable/src/api/functional/bbs/$package/articles/index.ts
  test/package.json
Labels: documentation, enhancement

#499 Upgrade `@nestia/migrate` following 1.5 spec
  packages/migrate/package.json
  packages/migrate/src/NestiaMigrateApplication.ts
  packages/migrate/src/archivers/FileArchiver.ts
  packages/migrate/src/programmers/RouteProgrammer.ts
  packages/migrate/src/structures/IMigrateRoute.ts
  packages/migrate/src/structures/ISwaggerRoute.ts
Labels: enhancement

#505 Support HTTP HEAD method
  .github/workflows/build.yml
  packages/core/package.json
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/fetcher/src/Fetcher.ts
  packages/fetcher/src/HttpError.ts
  packages/migrate/package.json
  packages/migrate/src/programmers/RouteProgrammer.ts
  packages/sdk/package.json
  packages/sdk/src/NestiaSdkApplication.ts
  packages/sdk/src/analyses/ControllerAnalyzer.ts
  packages/sdk/src/analyses/ReflectAnalyzer.ts
  packages/sdk/src/structures/IController.ts
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/features/method-error-get-body/nestia.config.ts
  test/features/method-error-get-body/src/api/structures/IBbsArticle.ts
  test/features/method-error-get-body/src/controllers/HealthController.ts
  test/features/method-error-get-body/src/controllers/MethodController.ts
  test/features/method-error-get-body/tsconfig.json
  test/features/method-error-head-body/api/structures/IBbsArticle.ts
  test/features/method-error-head-body/nestia.config.ts
  test/features/method-error-head-body/src/controllers/HealthController.ts
  test/features/method-error-head-body/src/controllers/MethodController.ts
  test/features/method-error-head-body/tsconfig.json
  test/features/method-error-head-non-void/nestia.config.ts
  test/features/method-error-head-non-void/src/api/structures/IBbsArticle.ts
  test/features/method-error-head-non-void/src/controllers/HealthController.ts
  test/features/method-error-head-non-void/src/controllers/MethodController.ts
  test/features/method-error-head-non-void/tsconfig.json
  test/features/method/nestia.config.ts
  test/features/method/src/Backend.ts
  test/features/method/src/api/HttpError.ts
  test/features/method/src/api/IConnection.ts
  test/features/method/src/api/Primitive.ts
  test/features/method/src/api/functional/health/index.ts
  test/features/method/src/api/functional/index.ts
  test/features/method/src/api/functional/method/index.ts
  test/features/method/src/api/functional/performance/index.ts
  test/features/method/src/api/index.ts
  test/features/method/src/api/module.ts
  test/features/method/src/api/structures/IPerformance.ts
  test/features/method/src/api/structures/ISystem.ts
  test/features/method/src/controllers/HealthController.ts
  test/features/method/src/controllers/MethodController.ts
  test/features/method/src/controllers/PerformanceController.ts
  test/features/method/src/test/features/api/automated/test_api_health_get.ts
  test/features/method/src/test/features/api/automated/test_api_method_head.ts
  test/features/method/src/test/features/api/automated/test_api_performance_get.ts
  test/features/method/src/test/features/api/test_api_health_check.ts
  test/features/method/src/test/features/api/test_api_method_head.ts
  test/features/method/src/test/features/api/test_api_performance.ts
  test/features/method/src/test/index.ts
  test/features/method/swagger.json
  test/features/method/tsconfig.json
  test/package.json
Labels: enhancement

#506 Fix #494: exact nullable type tracing in `@nestia/migrate`
  .github/workflows/build.yml
  packages/core/package.json
  packages/fetcher/package.json
  packages/fetcher/src/Fetcher.ts
  packages/migrate/package.json
  packages/migrate/src/NestiaMigrateApplication.ts
  packages/migrate/src/programmers/ControllerProgrammer.ts
  packages/migrate/src/programmers/DtoProgrammer.ts
  packages/migrate/src/programmers/ImportProgrammer.ts
  packages/migrate/src/programmers/MigrateProgrammer.ts
  packages/migrate/src/programmers/RouteProgrammer.ts
  packages/migrate/src/programmers/SchemaProgrammer.ts
  packages/sdk/package.json
  packages/sdk/src/generates/SwaggerGenerator.ts
  test/executable/start.js
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/features/method/swagger.json
  test/package.json
Labels: bug, enhancement

#513 Fix #512 - missed kebab case in real path
  packages/migrate/package.json
  packages/migrate/src/programmers/ControllerProgrammer.ts
  packages/migrate/src/programmers/RouteProgrammer.ts
  packages/migrate/src/test/index.ts
  packages/migrate/src/utils/StringUtil.ts
  test/features/kebab/nestia.config.ts
  test/features/kebab/src/Backend.ts
  test/features/kebab/src/api/HttpError.ts
  test/features/kebab/src/api/IConnection.ts
  test/features/kebab/src/api/Primitive.ts
  test/features/kebab/src/api/functional/health/index.ts
  test/features/kebab/src/api/functional/index.ts
  test/features/kebab/src/api/functional/ke_bab_with_dashes/index.ts
  test/features/kebab/src/api/functional/performance/index.ts
  test/features/kebab/src/api/index.ts
  test/features/kebab/src/api/module.ts
  test/features/kebab/src/api/structures/IBbsArticle.ts
  test/features/kebab/src/api/structures/IPerformance.ts
  test/features/kebab/src/api/structures/ISystem.ts
  test/features/kebab/src/controllers/HealthController.ts
  test/features/kebab/src/controllers/KebabController.ts
  test/features/kebab/src/controllers/PerformanceController.ts
  test/features/kebab/src/test/features/api/automated/test_api_health_get.ts
  test/features/kebab/src/test/features/api/automated/test_api_ke_bab_with_dashes_store.ts
  test/features/kebab/src/test/features/api/automated/test_api_performance_get.ts
  test/features/kebab/src/test/features/api/test_api_health_check.ts
  test/features/kebab/src/test/features/api/test_api_performance.ts
  test/features/kebab/src/test/index.ts
  test/features/kebab/swagger.json
  test/features/kebab/tsconfig.json
  test/package.json
Labels: bug

#518 Upgrade typia version to `1.4.16`
  packages/core/package.json
  packages/fetcher/package.json
  packages/fetcher/src/Fetcher.ts
  packages/migrate/package.json
  packages/sdk/package.json
Labels: bug

#519 Enhance `@nestia/fetcher` for `@EncryptedRoute`
  packages/core/package.json
  packages/fetcher/package.json
  packages/fetcher/src/Fetcher.ts
  packages/sdk/package.json
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/package.json
Labels: bug, documentation, enhancement

#520 Publish `@nestia/migrate@0.2.4` for updating bundled files
  packages/migrate/package.json
Labels: enhancement

#522 Fix #521 - swagger query parameter type must have specific name
  benchmark/package.json
  deploy/latest.sh
  deploy/next.sh
  packages/core/package.json
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
  packages/sdk/src/generates/SwaggerGenerator.ts
  packages/sdk/src/structures/ISwaggerRoute.ts
  test/executable/start.js
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/features/exception-filter/swagger.json
  test/features/fastify/swagger.json
  test/features/headers/swagger.json
  test/features/query/swagger.json
  test/features/simulate/swagger.json
  test/features/variable/swagger.json
  test/package.json
Labels: bug, enhancement

#524 Fix test program bug, not of main program
  test/executable/start.js
Labels: bug

#525 Enhance #446 add signal to IConnection.IOptions
  packages/fetcher/src/IConnection.ts
Labels: enhancement, good first issue

#526 Support `@All()` decorator of NestJS.
  packages/sdk/src/NestiaSdkApplication.ts
  packages/sdk/src/analyses/ControllerAnalyzer.ts
  packages/sdk/src/analyses/ReflectAnalyzer.ts
  packages/sdk/src/structures/IController.ts
  test/features/all/nestia.config.ts
  test/features/all/src/Backend.ts
  test/features/all/src/api/HttpError.ts
  test/features/all/src/api/IConnection.ts
  test/features/all/src/api/Primitive.ts
  test/features/all/src/api/functional/all/index.ts
  test/features/all/src/api/functional/health/index.ts
  test/features/all/src/api/functional/index.ts
  test/features/all/src/api/functional/performance/index.ts
  test/features/all/src/api/index.ts
  test/features/all/src/api/module.ts
  test/features/all/src/api/structures/IBbsArticle.ts
  test/features/all/src/api/structures/IPerformance.ts
  test/features/all/src/api/structures/ISystem.ts
  test/features/all/src/controllers/AllController.ts
  test/features/all/src/controllers/HealthController.ts
  test/features/all/src/controllers/PerformanceController.ts
  test/features/all/src/test/features/api/automated/test_api_all_store.ts
  test/features/all/src/test/features/api/automated/test_api_health_get.ts
  test/features/all/src/test/features/api/automated/test_api_performance_get.ts
  test/features/all/src/test/features/api/test_api_health_check.ts
  test/features/all/src/test/features/api/test_api_performance.ts
  test/features/all/src/test/index.ts
  test/features/all/swagger.json
  test/features/all/tsconfig.json
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/package.json
Labels: enhancement

#527 Fix samchon/typia#744 - change setup wizard to deprecate yarn berry
  packages/cli/package.json
  packages/cli/src/NestiaSetupWizard.ts
  packages/cli/src/internal/ArgumentParser.ts
Labels: bug, documentation, enhancement

#528 Complement samchon/typia#744 - change setup document contents
  website/pages/docs/setup.mdx
  website/public/sitemap-0.xml
Labels: enhancement

#534 Benchmark on Surface Pro 6
  benchmark/results/Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz/README.md
  benchmark/results/Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz/images/assert.svg
  benchmark/results/Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz/images/performance.svg
  benchmark/results/Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz/images/stringify.svg
Labels: documentation

#533 Update `typia` dependency version
  benchmark/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/package.json
Labels: enhancement

#537 Fix #489 - stop casting `typia.TypeGuardError` to 400 status code.
  benchmark/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/utils/ExceptionManager.ts
  packages/fetcher/package.json
  packages/migrate/assets/input/fireblocks.json
  packages/migrate/package.json
  packages/sdk/package.json
  test/package.json
  website/public/sitemap-0.xml
Labels: bug

#549 Complement #540 - `ISwaggerRoute.IResponseBody.description` is required.
  benchmark/package.json
  deploy/latest.sh
  packages/cli/package.json
  packages/core/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
  packages/sdk/src/generates/SwaggerGenerator.ts
  packages/sdk/src/generates/internal/SdkFunctionProgrammer.ts
  packages/sdk/src/structures/ISwaggerRoute.ts
  test/features/body-manual-assert/swagger.json
  test/features/body-manual-is/swagger.json
  test/features/body-manual-validate/swagger.json
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/features/encrypted/swagger.json
  test/features/equals/swagger.json
  test/features/exception-filter/swagger.json
  test/features/exception/src/controllers/ExceptionController.ts
  test/features/exception/swagger.json
  test/features/fastify/swagger.json
  test/features/headers-decompose/swagger.json
  test/features/headers/swagger.json
  test/features/non-equals/swagger.json
  test/features/plain/swagger.json
  test/features/query-decompose/swagger.json
  test/features/query/swagger.json
  test/features/simulate/swagger.json
  test/package.json
  website/pages/docs/core/TypedException.mdx
  website/pages/docs/core/_meta.json
  website/public/sitemap-0.xml
Labels: bug, enhancement

#567 Hold `typia@v5` update for a while
  packages/cli/package.json
  packages/cli/src/NestiaSetupWizard.ts
  packages/core/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
Labels: enhancement

#574 SDK distribution composer to use local version.
  packages/cli/package.json
  packages/core/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/assets/config/nestia.config.ts
  packages/sdk/package.json
  packages/sdk/src/generates/internal/DistributionComposer.ts
Labels: enhancement

#576 Fix mis-published `@nestia/migrate` bug
  packages/migrate/package.json
Labels: bug

#562 Adding the operation id
  packages/sdk/src/analyses/ControllerAnalyzer.ts
  packages/sdk/src/generates/SwaggerGenerator.ts
  packages/sdk/src/structures/IRoute.ts
  packages/sdk/src/structures/ISwaggerRoute.ts
Labels: enhancement
