Repository samchon/nestia, pull requests merged in 2023-11, with the labels that each got.

#678 Ignore wildcard URL case.
  benchmark/package.json
  packages/core/package.json
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
  packages/sdk/src/NestiaSdkApplication.ts
  packages/sdk/src/analyses/ReflectAnalyzer.ts
  packages/sdk/src/structures/IErrorReport.ts
  packages/sdk/src/structures/INestiaProject.ts
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/package.json
  website/pages/docs/sdk/sdk.mdx
Labels: bug, enhancement

#683 `ts.CompilerHost.jsDocParsingMode`
  benchmark/package.json
  build/index.js
  deploy/publish.js
  packages/core/package.json
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
  packages/sdk/src/NestiaSdkApplication.ts
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/package.json
  website/pages/docs/sdk/sdk.mdx
Labels: documentation, enhancement

#684 Fix #680 - when target type of `TypedException<T>` is union and shuffled
  packages/sdk/src/analyses/ExceptionAnalyzer.ts
  test/features/exception-with-propagate/nestia.config.ts
  test/features/exception-with-propagate/src/Backend.ts
  test/features/exception-with-propagate/src/api/HttpError.ts
  test/features/exception-with-propagate/src/api/IConnection.ts
  test/features/exception-with-propagate/src/api/Primitive.ts
  test/features/exception-with-propagate/src/api/functional/fail/index.ts
  test/features/exception-with-propagate/src/api/functional/index.ts
  test/features/exception-with-propagate/src/api/functional/success/index.ts
  test/features/exception-with-propagate/src/api/index.ts
  test/features/exception-with-propagate/src/api/module.ts
  test/features/exception-with-propagate/src/controllers/a_success.controller.ts
  test/features/exception-with-propagate/src/controllers/b_fail.controller.ts
  test/features/exception-with-propagate/src/filters/HttpExceptionFilter.ts
  test/features/exception-with-propagate/src/structures/ErrorCode.ts
  test/features/exception-with-propagate/src/test/features/api/fail.composite.ts
  test/features/exception-with-propagate/src/test/features/api/fail.ts
  test/features/exception-with-propagate/src/test/features/api/success.ts
  test/features/exception-with-propagate/src/test/features/api/success.union.ts
  test/features/exception-with-propagate/src/test/features/test_swagger.ts
  test/features/exception-with-propagate/src/test/index.ts
  test/features/exception-with-propagate/swagger.json
  test/features/exception-with-propagate/tsconfig.json
Labels: bug, enhancement, good first issue

#685 Safe nullish coalescing for speical cases
  packages/core/package.json
  packages/fetcher/package.json
  packages/sdk/package.json
  packages/sdk/src/analyses/GenericAnalyzer.ts
  packages/sdk/src/analyses/ImportAnalyzer.ts
  test/package.json
Labels: bug, enhancement

#691 Close #689: custom fetch
  packages/core/package.json
  packages/fetcher/package.json
  packages/fetcher/src/IConnection.ts
  packages/fetcher/src/internal/FetcherBase.ts
  packages/migrate/package.json
  packages/migrate/src/programmers/ControllerProgrammer.ts
  packages/migrate/src/programmers/MigrateProgrammer.ts
  packages/sdk/package.json
  packages/sdk/src/NestiaSdkApplication.ts
  packages/sdk/src/executable/sdk.ts
  test/package.json
Labels: enhancement

#692 Fix samchon/typia#880 - `any` type comes when `assertClone` option.
  packages/core/package.json
  packages/core/src/decorators/TypedBody.ts
  packages/fetcher/package.json
  packages/sdk/package.json
  test/package.json
Labels: bug

#695 Close #693 - `@ignore` comment tag.
  packages/core/package.json
  packages/fetcher/package.json
  packages/sdk/package.json
  packages/sdk/src/analyses/ControllerAnalyzer.ts
  test/features/ignore/nestia.config.ts
  test/features/ignore/src/Backend.ts
  test/features/ignore/src/api/HttpError.ts
  test/features/ignore/src/api/IConnection.ts
  test/features/ignore/src/api/Primitive.ts
  test/features/ignore/src/api/functional/bbs/articles/index.ts
  test/features/ignore/src/api/functional/bbs/index.ts
  test/features/ignore/src/api/functional/health/index.ts
  test/features/ignore/src/api/functional/index.ts
  test/features/ignore/src/api/functional/performance/index.ts
  test/features/ignore/src/api/index.ts
  test/features/ignore/src/api/module.ts
  test/features/ignore/src/api/structures/IBbsArticle.ts
  test/features/ignore/src/api/structures/IPerformance.ts
  test/features/ignore/src/api/structures/ISystem.ts
  test/features/ignore/src/controllers/BbsArticlesController.ts
  test/features/ignore/src/controllers/HealthController.ts
  test/features/ignore/src/controllers/PerformanceController.ts
  test/features/ignore/src/test/features/api/test_api_bbs_article_erase.ts
  test/features/ignore/src/test/features/api/test_api_bbs_article_store.ts
  test/features/ignore/src/test/features/api/test_api_bbs_article_update.ts
  test/features/ignore/src/test/features/api/test_api_health_check.ts
  test/features/ignore/src/test/features/api/test_api_performance.ts
  test/features/ignore/src/test/index.ts
  test/features/ignore/swagger.json
  test/features/ignore/tsconfig.json
  test/package.json
  website/pages/docs/sdk/sdk.mdx
  website/pages/docs/sdk/swagger.mdx
Labels: enhancement

#697 Update migrate and cli to suitable for v2.4 update.
  build/index.js
  deploy/publish.js
  packages/cli/package.json
  packages/cli/src/NestiaSetupWizard.ts
  packages/cli/src/internal/PackageManager.ts
  packages/migrate/package.json
Labels: enhancement
