Repository samchon/nestia, pull requests merged in 2024-07, with the labels that each got.

#940 `MigrateFetcher()` on `@nestia/fetcher`
  package.json
  packages/cli/package.json
  packages/cli/src/NestiaSetupWizard.ts
  packages/core/package.json
  packages/fetcher/package.json
  packages/fetcher/src/MigrateFetcher.ts
  packages/migrate/package.json
  packages/sdk/package.json
  test/features/migrate/migrate.json
  test/features/migrate/nestia.config.ts
  test/features/migrate/src/Backend.ts
  test/features/migrate/src/api/HttpError.ts
  test/features/migrate/src/api/IConnection.ts
  test/features/migrate/src/api/Primitive.ts
  test/features/migrate/src/api/functional/bbs/articles/index.ts
  test/features/migrate/src/api/functional/bbs/index.ts
  test/features/migrate/src/api/functional/index.ts
  test/features/migrate/src/api/functional/multipart/index.ts
  test/features/migrate/src/api/functional/query/index.ts
  test/features/migrate/src/api/index.ts
  test/features/migrate/src/api/module.ts
  test/features/migrate/src/api/structures/IAttachmentFile.ts
  test/features/migrate/src/api/structures/IBbsArticle.ts
  test/features/migrate/src/api/structures/IMultipart.ts
  test/features/migrate/src/api/structures/INestQuery.ts
  test/features/migrate/src/api/structures/IPage.ts
  test/features/migrate/src/api/structures/IQuery.ts
  test/features/migrate/src/controllers/BbsArticlesController.ts
  test/features/migrate/src/controllers/MultipartController.ts
  test/features/migrate/src/controllers/QueryController.ts
  test/features/migrate/src/test/ITestProps.ts
  test/features/migrate/src/test/features/api/test_api_bbs_article_at.ts
  test/features/migrate/src/test/features/api/test_api_bbs_article_create.ts
  test/features/migrate/src/test/features/api/test_api_bbs_article_index.ts
  test/features/migrate/src/test/features/api/test_api_bbs_article_update.ts
  test/features/migrate/src/test/features/api/test_api_multipart_post.ts
  test/features/migrate/src/test/features/api/test_api_query_body.ts
  test/features/migrate/src/test/features/api/test_api_query_composite.ts
  test/features/migrate/src/test/features/api/test_api_query_individual.ts
  test/features/migrate/src/test/features/api/test_api_query_nest.ts
  test/features/migrate/src/test/features/api/test_api_query_typed.ts
  test/features/migrate/src/test/index.ts
  test/features/migrate/swagger.json
  test/features/migrate/tsconfig.json
  test/package.json
  website/package-lock.json
  website/package.json
Labels: enhancement

#942 Upgrade `@samchon/openapi` dependency.
  benchmark/package.json
  package.json
  packages/core/package.json
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
  test/features/all/swagger.json
  test/features/app-globalPrefix-versionUri-routerModule/swagger.json
  test/features/app-globalPrefix-versionUri/swagger.json
  test/features/app-globalPrefix/swagger.json
  test/features/app-routerModule/swagger.json
  test/features/app-versionHeader/swagger.json
  test/features/app-versionUri/swagger.json
  test/features/app/swagger.json
  test/features/distribute-assert-json/packages/api/package.json
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/package.json
  website/package-lock.json
  website/package.json
  website/pages/docs/sdk/sdk.mdx
Labels: enhancement

#947 feat/docs: detailed options of swagger generator of `@nestia/sdk`.
  website/pages/docs/sdk/swagger.mdx
Labels: documentation

#948 Fix `INestiaConfig` type to be latest in docs
  packages/sdk/src/INestiaConfig.ts
  website/pages/docs/e2e/_meta.json
  website/pages/docs/sdk/e2e.mdx
  website/pages/docs/sdk/sdk.mdx
  website/pages/docs/sdk/simulator.mdx
  website/pages/docs/sdk/swagger.mdx
Labels: documentation

#946 Close #943: `config.swagger.decompose` to be default `true`.
  package.json
  packages/core/package.json
  packages/fetcher/package.json
  packages/sdk/package.json
  packages/sdk/src/INestiaConfig.ts
  packages/sdk/src/generates/internal/SwaggerSchemaGenerator.ts
  test/features/query-decompose-false/nestia.config.ts
  test/features/query-decompose-false/src/Backend.ts
  test/features/query-decompose-false/src/api/HttpError.ts
  test/features/query-decompose-false/src/api/IConnection.ts
  test/features/query-decompose-false/src/api/Primitive.ts
  test/features/query-decompose-false/src/api/functional/index.ts
  test/features/query-decompose-false/src/api/functional/query/index.ts
  test/features/query-decompose-false/src/api/index.ts
  test/features/query-decompose-false/src/api/module.ts
  test/features/query-decompose-false/src/api/structures/INestQuery.ts
  test/features/query-decompose-false/src/api/structures/IQuery.ts
  test/features/query-decompose-false/src/controllers/QueryController.ts
  test/features/query-decompose-false/src/test/features/api/test_api_query_composite.ts
  test/features/query-decompose-false/src/test/features/api/test_api_query_individual.ts
  test/features/query-decompose-false/src/test/features/api/test_api_query_invalid.ts
  test/features/query-decompose-false/src/test/features/api/test_api_query_nest.ts
  test/features/query-decompose-false/src/test/features/api/test_api_query_null.ts
  test/features/query-decompose-false/src/test/features/api/test_api_query_typed.ts
  test/features/query-decompose-false/src/test/features/test_swagger.ts
  test/features/query-decompose-false/src/test/index.ts
  test/features/query-decompose-false/swagger.json
  test/features/query-decompose-false/tsconfig.json
  test/features/query-decompose-true/nestia.config.ts
  test/features/query-decompose-true/src/Backend.ts
  test/features/query-decompose-true/src/api/HttpError.ts
  test/features/query-decompose-true/src/api/IConnection.ts
  test/features/query-decompose-true/src/api/Primitive.ts
  test/features/query-decompose-true/src/api/functional/index.ts
  test/features/query-decompose-true/src/api/functional/query/index.ts
  test/features/query-decompose-true/src/api/index.ts
  test/features/query-decompose-true/src/api/module.ts
  test/features/query-decompose-true/src/api/structures/INestQuery.ts
  test/features/query-decompose-true/src/api/structures/IQuery.ts
  test/features/query-decompose-true/src/controllers/QueryController.ts
  test/features/query-decompose-true/src/test/features/api/test_api_query_composite.ts
  test/features/query-decompose-true/src/test/features/api/test_api_query_individual.ts
  test/features/query-decompose-true/src/test/features/api/test_api_query_invalid.ts
  test/features/query-decompose-true/src/test/features/api/test_api_query_nest.ts
  test/features/query-decompose-true/src/test/features/api/test_api_query_null.ts
  test/features/query-decompose-true/src/test/features/api/test_api_query_typed.ts
  test/features/query-decompose-true/src/test/features/test_swagger.ts
  test/features/query-decompose-true/src/test/index.ts
  test/features/query-decompose-true/swagger.json
  test/features/query-decompose-true/tsconfig.json
  test/features/query-decompose/swagger.json
  test/features/query/swagger.json
  test/package.json
Labels: enhancement

#949 Features/optional query
  benchmark/package.json
  package.json
  packages/core/package.json
  packages/core/src/programmers/TypedQueryProgrammer.ts
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
  packages/sdk/src/INestiaConfig.ts
  packages/sdk/src/analyses/TypedHttpOperationAnalyzer.ts
  packages/sdk/src/generates/internal/SdkHttpNamespaceProgrammer.ts
  packages/sdk/src/generates/internal/SwaggerSchemaValidator.ts
  test/features/distribute-assert-json/packages/api/package.json
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/features/query-decompose/swagger.json
  test/features/query-error-optional/nestia.config.ts
  test/features/query-error-optional/src/Backend.ts
  test/features/query-error-optional/src/controllers/QueryController.ts
  test/features/query-error-optional/swagger.json
  test/features/query-error-optional/tsconfig.json
  test/features/query/src/api/functional/query/index.ts
  test/features/query/src/api/structures/IOptionalQuery.ts
  test/features/query/src/controllers/QueryController.ts
  test/features/query/src/test/features/api/test_api_query_optional.ts
  test/features/query/swagger.json
  test/package.json
  website/package.json
  website/pages/docs/e2e/_meta.json
  website/pages/docs/sdk/e2e.mdx
  website/pages/docs/sdk/sdk.mdx
  website/pages/docs/sdk/simulator.mdx
  website/pages/docs/sdk/swagger.mdx
Labels: enhancement

#954 New decorator `@SwaggerExample()`.
  package.json
  packages/core/package.json
  packages/core/src/decorators/SwaggerExample.ts
  packages/core/src/decorators/WebSocketRoute.ts
  packages/core/src/module.ts
  packages/fetcher/package.json
  packages/sdk/package.json
  packages/sdk/src/analyses/ReflectHttpOperationAnalyzer.ts
  packages/sdk/src/analyses/TypedHttpOperationAnalyzer.ts
  packages/sdk/src/generates/internal/SwaggerSchemaGenerator.ts
  packages/sdk/src/structures/IReflectHttpOperation.ts
  packages/sdk/src/structures/ITypedHttpRoute.ts
  test/features/security/src/controllers/SecurityController.ts
  test/features/swagger-example/nestia.config.ts
  test/features/swagger-example/src/Backend.ts
  test/features/swagger-example/src/api/HttpError.ts
  test/features/swagger-example/src/api/IConnection.ts
  test/features/swagger-example/src/api/Primitive.ts
  test/features/swagger-example/src/api/functional/bbs/articles/index.ts
  test/features/swagger-example/src/api/functional/bbs/index.ts
  test/features/swagger-example/src/api/functional/index.ts
  test/features/swagger-example/src/api/index.ts
  test/features/swagger-example/src/api/module.ts
  test/features/swagger-example/src/api/structures/IBbsArticle.ts
  test/features/swagger-example/src/controllers/BbsArticlesController.ts
  test/features/swagger-example/src/test/features/test_swagger_example.ts
  test/features/swagger-example/src/test/index.ts
  test/features/swagger-example/swagger.json
  test/features/swagger-example/tsconfig.json
  test/package.json
Labels: enhancement

#955 Bump up `@samchon/openapi` version for `@SwaggerExample()`.
  benchmark/package.json
  package.json
  packages/benchmark/package.json
  packages/core/package.json
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
  test/features/distribute-assert-json/packages/api/package.json
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/package.json
Labels: enhancement

#956 API Documents for every packages
  .gitignore
  packages/benchmark/typedoc.json
  packages/core/typedoc.json
  packages/e2e/tsconfig.json
  packages/e2e/typedoc.json
  packages/fetcher/typedoc.json
  test/package.json
  website/.gitignore
  website/build/typedoc.js
  website/package-lock.json
  website/package.json
  website/typedoc.json
Labels: documentation

#957 `@nestia/migrate` also supports `@SwaggerExample()`.
  packages/core/package.json
  packages/migrate/assets/input/v3.1/example31.json
  packages/migrate/package.json
  packages/migrate/src/programmers/MigrateNestMethodProgrammer.ts
  packages/sdk/package.json
  website/build/typedoc.js
  website/package-lock.json
  website/package.json
Labels: enhancement

#958 Fix `@nestia/editor`'s mode bug
  website/package-lock.json
  website/src/movies/editor/EditorMovie.tsx
Labels: bug, documentation, enhancement

#959 Let CLI to setup `@nestia/benchmark` too.
  packages/cli/package.json
  packages/cli/src/NestiaSetupWizard.ts
Labels: enhancement

#960 fix/docs: replace FastifyAdaptor with FastifyAdapter
  packages/sdk/assets/config/nestia.config.ts
  website/pages/docs/sdk/e2e.mdx
  website/pages/docs/sdk/sdk.mdx
  website/pages/docs/sdk/simulator.mdx
  website/pages/docs/sdk/swagger.mdx
Labels: bug

#961 Exact documentation of `@nestia/benchmark`
  packages/benchmark/package.json
  packages/benchmark/src/DynamicBenchmarker.ts
  website/pages/docs/e2e/benchmark.mdx
  website/pages/docs/e2e/why.mdx
Labels: documentation, enhancement

#962 Add `MigrateFetcher.propagate()` function.
  package.json
  packages/core/package.json
  packages/fetcher/package.json
  packages/fetcher/src/MigrateFetcher.ts
  packages/sdk/package.json
  test/features/migrate/migrate.json
  test/features/migrate/src/test/features/api/test_api_bbs_article_at.ts
  test/features/migrate/swagger.json
  test/features/propagate/src/test/features/api/automated/test_api_members_login.ts
  test/package.json
Labels: enhancement

#964 Prohibit `TypedFormData.Body()` function in older NodeJS version.
  packages/core/src/decorators/TypedFormData.ts
Labels: enhancement

#963 Bump up `typia` version and update `Primitive` type to be compatible.
  benchmark/package.json
  package.json
  packages/benchmark/package.json
  packages/core/package.json
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/fetcher/src/Primitive.ts
  packages/fetcher/src/Resolved.ts
  packages/migrate/package.json
  packages/sdk/package.json
  test/features/date/src/api/structures/IDateDefined.ts
  test/features/date/tsconfig.json
  test/features/distribute-assert-json/packages/api/package.json
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/package.json
  website/package.json
Labels: enhancement

#967 Documentation of OpenAI function calling schemas generator.
  website/package-lock.json
  website/pages/docs/index.mdx
  website/pages/docs/sdk/_meta.json
  website/pages/docs/sdk/openai.mdx
  website/pages/docs/sdk/sdk.mdx
  website/pages/docs/sdk/swagger.mdx
Labels: documentation, enhancement

#968 Fix #966: support `jsx` configured case.
  packages/sdk/package.json
  packages/sdk/src/executable/internal/NestiaConfigLoader.ts
Labels: enhancement, good first issue

#970 Add memory consumption graph in benchmark program.
  packages/benchmark/package.json
  packages/benchmark/src/DynamicBenchmarker.ts
  packages/benchmark/src/internal/DynamicBenchmarkReporter.ts
  packages/benchmark/test/index.ts
  packages/migrate/package.json
  website/pages/docs/e2e/why.mdx
  website/public/images/benchmark-dark.png
  website/public/images/benchmark.png
Labels: documentation, enhancement

#973 Bump up dependencies of `migrate` and `editor`.
  packages/migrate/package.json
  website/package.json
Labels: enhancement

#975 Fix #974: allow implicit type on swagger generator again.
  benchmark/package.json
  package.json
  packages/benchmark/package.json
  packages/core/package.json
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
  packages/sdk/src/NestiaSdkApplication.ts
  packages/sdk/src/generates/SdkGenerator.ts
  test/features/distribute-assert-json/packages/api/package.json
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/package.json
  website/package.json
Labels: bug, enhancement

#976 Bump up migrate dependencies
  packages/migrate/package.json
Labels: enhancement
