Repository samchon/nestia, pull requests merged in 2024-03, with the labels that each got.

#827 Enhance `@nestia/migrate` for non-standard case.
  package.json
  packages/core/package.json
  packages/core/src/structures/ISwaggerSecurityScheme.ts
  packages/fetcher/package.json
  packages/migrate/assets/input/petstore.json
  packages/migrate/package.json
  packages/migrate/src/analyzers/MigrateMethodAnalyzer.ts
  packages/migrate/src/structures/ISwaggerSecurityScheme.ts
  packages/sdk/package.json
  packages/sdk/src/structures/ISwaggerSecurityScheme.ts
  test/package.json
  website/package.json
  website/public/sitemap-0.xml
Labels: enhancement

#828 Simplify `PlainFetcher` and `EncryptedFetcher`.
  package.json
  packages/core/package.json
  packages/fetcher/package.json
  packages/fetcher/src/EncryptedFetcher.ts
  packages/fetcher/src/PlainFetcher.ts
  packages/fetcher/src/internal/FetcherBase.ts
  packages/sdk/package.json
  test/package.json
Labels: enhancement

#829 Adjust samchon/typia#999: upgrade typia dependency
  benchmark/package.json
  package.json
  packages/cli/package.json
  packages/cli/src/NestiaSetupWizard.ts
  packages/core/package.json
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
  test/features/distribute-assert-json/packages/api/package.json
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/package.json
  website/package.json
  website/pages/docs/sdk/sdk.mdx
Labels: bug, enhancement

#833 feat: add wrapper parameters
  packages/e2e/src/DynamicExecutor.ts
Labels: bug, enhancement

#840 Fix #837: critical API change from NestJS 10.3.4 update.
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/website.yml
  package.json
  packages/core/package.json
  packages/fetcher/package.json
  packages/sdk/package.json
  packages/sdk/src/analyses/ReflectAnalyzer.ts
  packages/sdk/src/structures/ParamCategory.ts
  test/features/all/swagger.json
  test/features/app-globalPrefix-versionUri-routerModule/swagger.json
  test/features/app-globalPrefix-versionUri/swagger.json
  test/features/app-globalPrefix/swagger.json
  test/features/app-routerModule/swagger.json
  test/features/app-versionHeader/swagger.json
  test/features/app-versionUri/swagger.json
  test/features/app/swagger.json
  test/features/beautify-4/swagger.json
  test/features/beautify-false/swagger.json
  test/features/beautify/swagger.json
  test/features/body-config-assert/swagger.json
  test/features/body-config-assertClone/swagger.json
  test/features/body-config-assertEquals/swagger.json
  test/features/body-config-assertPrune/swagger.json
  test/features/body-config-equals/swagger.json
  test/features/body-config-is/swagger.json
  test/features/body-config-validate/swagger.json
  test/features/body-config-validateClone/swagger.json
  test/features/body-config-validateEquals/swagger.json
  test/features/body-config-validatePrune/swagger.json
  test/features/body/swagger.json
  test/features/headers-decompose/swagger.json
  test/features/headers/swagger.json
  test/package.json
  website/package.json
Labels: bug, enhancement

#841 Enhance `ISwaggerComponents` type of `@nestia/migrate`.
  packages/migrate/assets/input/damoa.json
  packages/migrate/package.json
  packages/migrate/src/analyzers/MigrateControllerAnalyzer.ts
  packages/migrate/src/analyzers/MigrateMethodAnalyzer.ts
  packages/migrate/src/programmers/MigrateSchemaProgrammer.ts
  packages/migrate/src/structures/ISwagger.ts
  packages/migrate/src/structures/ISwaggerComponents.ts
  packages/migrate/src/structures/ISwaggerRoute.ts
  packages/migrate/src/structures/ISwaggerRouteBodyContent.ts
  packages/migrate/src/structures/ISwaggerRouteHeader.ts
  packages/migrate/src/structures/ISwaggerRouteParameter.ts
  packages/migrate/src/structures/ISwaggerRouteRequestBody.ts
  packages/migrate/src/structures/ISwaggerRouteResponse.ts
  packages/migrate/src/utils/SwaggerComponentsExplorer.ts
  packages/migrate/src/utils/SwaggerTypeChecker.ts
  website/package.json
  website/public/sitemap-0.xml
Labels: enhancement

#842 Support `yaml` file in the `@nestia/editor`
  website/package.json
  website/src/components/editor/EditorUploader.tsx
Labels: enhancement

#844 Complement #837 - critical API change from NestJS 10.3.5 update.
  package.json
  packages/core/package.json
  packages/fetcher/package.json
  packages/sdk/package.json
  packages/sdk/src/analyses/ReflectAnalyzer.ts
  test/features/headers-decompose/swagger.json
  test/features/headers/swagger.json
  test/features/ignore/swagger.json
  test/package.json
Labels: bug, enhancement

#845 `@nestia/migrate` support to every swagger versions.
  packages/migrate/assets/input/openapiv3.1.json
  packages/migrate/assets/input/swaggerv2.0.json
  packages/migrate/package.json
  packages/migrate/src/MigrateApplication.ts
  packages/migrate/src/internal/MigrateCommander.ts
  packages/migrate/src/structures/ISwaggerV20.ts
  packages/migrate/src/structures/ISwaggerV31.ts
  packages/migrate/src/test/index.ts
  packages/migrate/src/utils/OpenApiConverter.ts
  website/package.json
  website/pages/docs/editor.mdx
  website/pages/docs/migrate.mdx
Labels: enhancement

#846 Discard swagger v2 supporting from `@nestia/migrate`.
  packages/migrate/assets/input/swaggerv2.0.json
  packages/migrate/package.json
  packages/migrate/src/MigrateApplication.ts
  packages/migrate/src/utils/OpenApiConverter.ts
  website/package.json
  website/pages/docs/editor.mdx
  website/pages/docs/migrate.mdx
Labels: enhancement

#850 Fix `@nestia/migrate` bug of return type skipping
  packages/migrate/assets/input/example.json
  packages/migrate/package.json
  packages/migrate/src/analyzers/MigrateMethodAnalyzer.ts
  website/package.json
Labels: bug

#852 Make compatible with https://esm.sh
  package.json
  packages/core/package.json
  packages/fetcher/package.json
  packages/fetcher/src/internal/FetcherBase.ts
  packages/migrate/package.json
  packages/sdk/package.json
  test/features/app-globalPrefix/src/api/HttpError.ts
  test/package.json
Labels: enhancement

#853 Adapt `tstl@v3` update.
  benchmark/package.json
  benchmark/src/generate/BenchmarkProgrammer.ts
  benchmark/src/generate/assert.ts
  benchmark/src/generate/performance.ts
  benchmark/src/generate/stringify.ts
  benchmark/src/internal/BenchmarkServer.ts
  benchmark/src/internal/BenchmarktReporter.ts
  benchmark/src/internal/BenhmarkStream.ts
  benchmark/src/internal/HorizontalBarChart.ts
  benchmark/src/programs/IBenchmarkProgram.ts
  benchmark/src/programs/assert/servers/createNestExpressAssertProgram.ts
  benchmark/src/programs/assert/servers/createNestFastifyAssertProgram.ts
  benchmark/src/programs/performance/servers/createNestExpressPerformanceProgram.ts
  benchmark/src/programs/performance/servers/createNestFastifyPerformanceProgram.ts
  benchmark/src/programs/stringify/servers/createAjvStringifyProgram.ts
  benchmark/src/programs/stringify/servers/createNestExpressStringifyProgram.ts
  benchmark/src/programs/stringify/servers/createNestFastifyStringifyProgram.ts
  package.json
  packages/core/package.json
  packages/e2e/package.json
  packages/e2e/src/RandomGenerator.ts
  packages/e2e/src/TestValidator.ts
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
  packages/sdk/src/analyses/ControllerAnalyzer.ts
  packages/sdk/src/analyses/ImportAnalyzer.ts
  packages/sdk/src/analyses/ReflectAnalyzer.ts
  packages/sdk/src/generates/SwaggerGenerator.ts
  packages/sdk/src/generates/internal/ImportDictionary.ts
  packages/sdk/src/structures/TypeEntry.ts
  test/package.json
Labels: enhancement

#854 `@nestia/editor` contains swagger-ui
  packages/migrate/package.json
  packages/migrate/src/MigrateApplication.ts
  website/package.json
  website/pages/docs/editor.mdx
  website/pages/docs/migrate.mdx
  website/public/images/editor/stackblitz.png
  website/src/movies/editor/EditorMovie.tsx
Labels: enhancement

#856 Fix github actions bug by `@nestia/editor` template
  packages/migrate/package.json
  website/.gitignore
  website/public/articles/stop-using-swagger-ui-only-but-go-with-typescript-sdk.html
Labels: bug
