Repository samchon/nestia, pull requests merged in 2024-02, with the labels that each got.

#781 Roll `@nestia/migrate` back to the `exrpess` for `@TypedFormData.Body()`
  packages/migrate/package.json
Labels: enhancement

#783 Refactoring of `@nestia/migrate`.
  packages/migrate/package.json
  packages/migrate/src/MigrateApplication.ts
  packages/migrate/src/analyzers/MigrateAnalyzer.ts
  packages/migrate/src/analyzers/MigrateControllerAnalyzer.ts
  packages/migrate/src/analyzers/MigrateMethodAnalyzer.ts
  packages/migrate/src/archivers/MigrateFileArchiver.ts
  packages/migrate/src/executable/bundle.ts
  packages/migrate/src/internal/MigrateCommander.ts
  packages/migrate/src/programmers/MigrateApiFileProgrammer.ts
  packages/migrate/src/programmers/MigrateApiFunctionProgrammer.ts
  packages/migrate/src/programmers/MigrateApiNamespaceProgrammer.ts
  packages/migrate/src/programmers/MigrateApiProgrammer.ts
  packages/migrate/src/programmers/MigrateApiSimulatationProgrammer.ts
  packages/migrate/src/programmers/MigrateDtoProgrammer.ts
  packages/migrate/src/programmers/MigrateImportProgrammer.ts
  packages/migrate/src/programmers/MigrateNestControllerProgrammer.ts
  packages/migrate/src/programmers/MigrateNestMethodProgrammer.ts
  packages/migrate/src/programmers/MigrateNestModuleProgrammer.ts
  packages/migrate/src/programmers/MigrateNestProgrammer.ts
  packages/migrate/src/programmers/MigrateSchemaProgrammer.ts
  packages/migrate/src/structures/IMigrateRoute.ts
  packages/migrate/src/test/index.ts
  packages/migrate/src/utils/FilePrinter.ts
  packages/migrate/src/utils/SwaggerTypeChecker.ts
Labels: enhancement

#784 Complete refactoring of `@nestia/migrate`
  packages/migrate/package.json
  packages/migrate/src/IMigrateConfig.ts
  packages/migrate/src/MigrateApplication.ts
  packages/migrate/src/analyzers/MigrateAnalyzer.ts
  packages/migrate/src/analyzers/MigrateControllerAnalyzer.ts
  packages/migrate/src/analyzers/MigrateMethodAnalyzer.ts
  packages/migrate/src/module.ts
  packages/migrate/src/programmers/MigrateApiFileProgrammer.ts
  packages/migrate/src/programmers/MigrateApiFunctionProgrammer.ts
  packages/migrate/src/programmers/MigrateApiNamespaceProgrammer.ts
  packages/migrate/src/programmers/MigrateApiProgrammer.ts
  packages/migrate/src/programmers/MigrateDtoProgrammer.ts
  packages/migrate/src/programmers/MigrateImportProgrammer.ts
  packages/migrate/src/programmers/MigrateNestMethodProgrammer.ts
  packages/migrate/src/programmers/MigrateSchemaProgrammer.ts
  packages/migrate/src/structures/IMigrateDto.ts
  packages/migrate/src/structures/IMigrateProgram.ts
  packages/migrate/src/structures/IMigrateRoute.ts
  packages/migrate/src/structures/ISwaggerComponents.ts
  packages/migrate/src/structures/ISwaggerRoute.ts
  packages/migrate/src/structures/ISwaggerSchema.ts
  packages/migrate/src/test/index.ts
  packages/migrate/src/utils/SwaggerTypeChecker.ts
Labels: enhancement

#786 Beautify `@nestia/migrate` generated files.
  package.json
  packages/migrate/package.json
  packages/migrate/src/internal/MigrateCommander.ts
  packages/migrate/src/programmers/MigrateNestModuleProgrammer.ts
  packages/migrate/src/test/index.ts
  packages/sdk/src/generates/SwaggerGenerator.ts
Labels: enhancement

#787 Main intro page
  website/package.json
  website/pages/_meta.json
  website/pages/index.mdx
  website/public/images/home/background.png
  website/public/images/home/productHeroArrowDown.png
  website/public/images/home/random.png
  website/public/images/home/sdk.png
  website/public/images/home/swagger.png
  website/public/sitemap-0.xml
  website/src/components/home/HomeCodeBlock.tsx
  website/src/components/home/HomeLayout.tsx
  website/src/components/home/ProductHeroLayout.tsx
  website/src/movies/home/HomeHeroMovie.tsx
  website/src/movies/home/HomeStrengthMovie.tsx
  website/src/movies/home/HomeStrengthSectionMovie.tsx
Labels: enhancement

#792 Refactor `@nestia/migrate` for 3rd party app.
  packages/migrate/package.json
  packages/migrate/src/analyzers/MigrateMethodAnalyzer.ts
  packages/migrate/src/programmers/MigrateApiProgrammer.ts
  packages/migrate/src/programmers/MigrateDtoProgrammer.ts
  packages/migrate/src/programmers/MigrateImportProgrammer.ts
  packages/migrate/src/programmers/MigrateNestProgrammer.ts
  packages/migrate/src/structures/IMigrateRoute.ts
Labels: enhancement

#793 Inform `@TypedBody()` is not essential for SDK generation.
  README.md
  packages/core/package.json
  packages/sdk/package.json
  test/package.json
  website/pages/docs/_meta.json
  website/pages/docs/core/TypedBody.mdx
  website/pages/docs/core/TypedHeaders.mdx
  website/pages/docs/core/TypedParam.mdx
  website/pages/docs/core/TypedQuery.mdx
  website/pages/docs/core/TypedRoute.mdx
  website/pages/docs/index.mdx
  website/pages/docs/migrate.mdx
  website/pages/docs/sdk/sdk.mdx
  website/pages/docs/sdk/simulator.mdx
  website/public/sitemap-0.xml
Labels: documentation

#794 Introduce `clone` mode in the `docs/sdk/sdk.mdx`
  website/next.config.js
  website/package.json
  website/pages/docs/_meta.json
  website/pages/docs/core/_meta.json
  website/pages/docs/sdk/sdk.mdx
  website/public/sitemap-0.xml
Labels: documentation

#798 fix nestia core dependencies
  packages/core/package.json
Labels: good first issue, invalid, question, wontfix

#801 Introduce `nestia.config.ts` setup on platform `fastify`
  packages/sdk/assets/config/nestia.config.ts
  website/pages/docs/sdk/e2e.mdx
  website/pages/docs/sdk/sdk.mdx
  website/pages/docs/sdk/simulator.mdx
  website/pages/docs/sdk/swagger.mdx
  website/public/sitemap-0.xml
Labels: documentation

#802 Enhance `@nestia/migrate` to generate e2e test functions.
  packages/migrate/package.json
  packages/migrate/src/MigrateApplication.ts
  packages/migrate/src/executable/bundle.ts
  packages/migrate/src/internal/MigrateCommander.ts
  packages/migrate/src/internal/MigrateInquirer.ts
  packages/migrate/src/programmers/MigrateApiStartProgrammer.ts
  packages/migrate/src/programmers/MigrateE2eFileProgrammer.ts
  packages/migrate/src/programmers/MigrateE2eProgrammer.ts
  packages/migrate/src/structures/IMigrateProgram.ts
  packages/migrate/src/test/index.ts
  website/pages/docs/migrate.mdx
  website/public/sitemap-0.xml
Labels: enhancement

#803 Close #445 - TypeScript Swagger Editor
  README.md
  deploy/publish.js
  packages/core/README.md
  packages/core/package.json
  packages/fetcher/README.md
  packages/migrate/README.md
  packages/migrate/assets/input/bbs.json
  packages/migrate/assets/input/shopping.json
  packages/migrate/package.json
  packages/migrate/src/MigrateApplication.ts
  packages/migrate/src/analyzers/MigrateControllerAnalyzer.ts
  packages/migrate/src/analyzers/MigrateMethodAnalyzer.ts
  packages/migrate/src/internal/MigrateCommander.ts
  packages/migrate/src/programmers/MigrateApiFileProgrammer.ts
  packages/migrate/src/programmers/MigrateApiFunctionProgrammer.ts
  packages/migrate/src/programmers/MigrateApiNamespaceProgrammer.ts
  packages/migrate/src/programmers/MigrateApiProgrammer.ts
  packages/migrate/src/programmers/MigrateE2eFileProgrammer.ts
  packages/migrate/src/programmers/MigrateE2eProgrammer.ts
  packages/migrate/src/programmers/MigrateNestMethodProgrammer.ts
  packages/migrate/src/structures/IMigrateRoute.ts
  packages/sdk/README.md
  packages/sdk/package.json
  prettier.config.js
  test/package.json
  website/package.json
  website/pages/docs/_meta.json
  website/pages/docs/editor.mdx
  website/pages/docs/index.mdx
  website/pages/docs/migrate.mdx
  website/public/images/editor/stackblitz.png
  website/public/sitemap-0.xml
  website/src/components/editor/EditorUploader.tsx
  website/src/movies/editor/EditorMovie.tsx
  website/src/movies/home/HomeStrengthMovie.tsx
Labels: documentation, enhancement, good first issue

#804 fix: embed nestia dependency
  website/pages/docs/editor.mdx
  website/pages/docs/migrate.mdx
  website/pages/docs/setup.mdx
Labels: documentation, enhancement, good first issue

#807 Add discord badge
  .github/workflows/build.yml
  README.md
  packages/core/README.md
  packages/fetcher/README.md
  packages/sdk/README.md
  website/pages/docs/index.mdx
Labels: documentation, enhancement

#808 Fix `@nestia/migrate` bug of omitting `@TypedRoute()`.
  packages/migrate/assets/input/bbs.json
  packages/migrate/assets/input/shopping.json
  packages/migrate/package.json
  packages/migrate/src/programmers/MigrateApiNamespaceProgrammer.ts
  packages/migrate/src/programmers/MigrateNestMethodProgrammer.ts
Labels: bug, enhancement

#809 `@nestia/editor` supports both SDK and NestJS
  website/package.json
  website/pages/docs/editor.mdx
  website/pages/docs/migrate.mdx
  website/src/movies/editor/EditorMovie.tsx
Labels: documentation, enhancement

#811 Close #810 - `@SwaggerCustomizer()`
  package.json
  packages/core/package.json
  packages/core/src/decorators/SwaggerCustomizer.ts
  packages/core/src/module.ts
  packages/core/src/structures/ISwagger.ts
  packages/core/src/structures/ISwaggerComponents.ts
  packages/core/src/structures/ISwaggerInfo.ts
  packages/core/src/structures/ISwaggerRoute.ts
  packages/core/src/structures/ISwaggerSecurityScheme.ts
  packages/fetcher/package.json
  packages/sdk/package.json
  packages/sdk/src/analyses/ControllerAnalyzer.ts
  packages/sdk/src/analyses/ReflectAnalyzer.ts
  packages/sdk/src/generates/SwaggerGenerator.ts
  packages/sdk/src/structures/IController.ts
  packages/sdk/src/structures/IRoute.ts
  test/features/swagger-customizer/nestia.config.ts
  test/features/swagger-customizer/src/Backend.ts
  test/features/swagger-customizer/src/api/HttpError.ts
  test/features/swagger-customizer/src/api/IConnection.ts
  test/features/swagger-customizer/src/api/Primitive.ts
  test/features/swagger-customizer/src/api/functional/index.ts
  test/features/swagger-customizer/src/api/functional/swagger/index.ts
  test/features/swagger-customizer/src/api/index.ts
  test/features/swagger-customizer/src/api/module.ts
  test/features/swagger-customizer/src/api/structures/IPerformance.ts
  test/features/swagger-customizer/src/api/structures/ISystem.ts
  test/features/swagger-customizer/src/controllers/SwaggerController.ts
  test/features/swagger-customizer/src/test/features/test_swagger_file.ts
  test/features/swagger-customizer/src/test/index.ts
  test/features/swagger-customizer/swagger.json
  test/features/swagger-customizer/tsconfig.json
  test/package.json
Labels: enhancement

#814 Enhance #810 - multiple customization + `at()` method
  package.json
  packages/core/package.json
  packages/core/src/decorators/SwaggerCustomizer.ts
  packages/fetcher/package.json
  packages/sdk/package.json
  packages/sdk/src/NestiaSdkApplication.ts
  packages/sdk/src/analyses/ControllerAnalyzer.ts
  packages/sdk/src/analyses/ReflectAnalyzer.ts
  packages/sdk/src/generates/SwaggerGenerator.ts
  packages/sdk/src/generates/internal/SdkRouteProgrammer.ts
  packages/sdk/src/structures/IController.ts
  packages/sdk/src/structures/IRoute.ts
  test/features/all/swagger.json
  test/features/app-globalPrefix-versionUri-routerModule/swagger.json
  test/features/app-globalPrefix-versionUri/swagger.json
  test/features/app-globalPrefix/swagger.json
  test/features/app-routerModule/src/api/IConnection.ts
  test/features/app-routerModule/swagger.json
  test/features/app-versionHeader/swagger.json
  test/features/app-versionUri/swagger.json
  test/features/app/swagger.json
  test/features/beautify-4/swagger.json
  test/features/beautify-false/swagger.json
  test/features/beautify/swagger.json
  test/features/body-config-assert/swagger.json
  test/features/body-config-assertClone/swagger.json
  test/features/body-config-assertEquals/swagger.json
  test/features/body-config-assertPrune/swagger.json
  test/features/body-config-equals/swagger.json
  test/features/body-config-is/swagger.json
  test/features/body-config-validate/swagger.json
  test/features/body-config-validateClone/swagger.json
  test/features/body-config-validateEquals/swagger.json
  test/features/body-config-validatePrune/swagger.json
  test/features/body-manual-assert/swagger.json
  test/features/body-manual-is/swagger.json
  test/features/body-manual-validate/swagger.json
  test/features/body/swagger.json
  test/features/swagger-customizer/src/api/functional/custom/index.ts
  test/features/swagger-customizer/src/api/functional/index.ts
  test/features/swagger-customizer/src/controllers/SwaggerController.ts
  test/features/swagger-customizer/src/decorators/SelectorParam.ts
  test/features/swagger-customizer/src/test/features/test_swagger_file.ts
  test/features/swagger-customizer/swagger.json
  test/package.json
  website/pages/docs/sdk/swagger.mdx
Labels: enhancement

#815 Refactor `@nestia/migrate` for 3rd party application.
  packages/migrate/package.json
  packages/migrate/src/programmers/MigrateImportProgrammer.ts
  packages/migrate/src/programmers/MigrateSchemaProgrammer.ts
  packages/migrate/src/structures/ISwaggerComponents.ts
Labels: enhancement

#818 Fix #816 - `@TypedException<T>()` when namespaced type comes.
  package.json
  packages/core/package.json
  packages/core/src/decorators/TypedException.ts
  packages/core/src/programmers/TypedExceptionProgrammer.ts
  packages/fetcher/package.json
  packages/sdk/package.json
  packages/sdk/src/analyses/ExceptionAnalyzer.ts
  test/features/exception-filter/swagger.json
  test/features/exception-with-propagate/swagger.json
  test/features/exception/nestia.config.ts
  test/features/exception/src/api/functional/exception/index.ts
  test/features/exception/src/api/structures/IExceptional.ts
  test/features/exception/src/controllers/ExceptionController.ts
  test/features/exception/src/test/features/api/automated/test_api_exception_union.ts
  test/features/exception/src/test/features/test_swagger.ts
  test/features/exception/swagger.json
  test/features/exception/tsconfig.json
  test/package.json
Labels: bug, enhancement
