Repository samchon/nestia, pull requests merged in 2024-09, with the labels that each got.

#1008 Close #1006: support URL inpput in `@nestia/migrate`
  packages/migrate/package.json
  packages/migrate/src/internal/MigrateCommander.ts
Labels: enhancement

#1013 Review sitemap.xml file
  website/deploy.js
  website/package.json
Labels: enhancement

#1019 Fix cli bug of runtime configuration
  packages/cli/package.json
  packages/cli/src/internal/ArgumentParser.ts
  packages/cli/src/internal/PluginConfigurator.ts
Labels: bug, enhancement

#1020 Update GenericAnalyzer.ts
  packages/sdk/src/analyses/GenericAnalyzer.ts
Labels: bug, enhancement, good first issue

#1021 Package manager detection like samchon/typia#1245.
  .github/dependabot.yml
  packages/cli/package.json
  packages/cli/src/NestiaSetupWizard.ts
  packages/cli/src/index.ts
  packages/cli/src/internal/ArgumentParser.ts
  packages/cli/src/internal/PackageManager.ts
Labels: enhancement

#1026 Hold #1016 for a while, because it needs a lot of change in `typia`.
  test/features/clone-type-create-duplicate/sdk/HttpError.ts
  test/features/clone-type-create-duplicate/sdk/IConnection.ts
  test/features/clone-type-create-duplicate/sdk/Primitive.ts
  test/features/clone-type-create-duplicate/sdk/Resolved.ts
  test/features/clone-type-create-duplicate/sdk/functional/auth/index.ts
  test/features/clone-type-create-duplicate/sdk/functional/index.ts
  test/features/clone-type-create-duplicate/sdk/functional/user/index.ts
  test/features/clone-type-create-duplicate/sdk/index.ts
  test/features/clone-type-create-duplicate/sdk/module.ts
  test/features/clone-type-create-duplicate/sdk/structures/Exception.ts
  test/features/clone-type-create-duplicate/sdk/structures/IAuth.ts
  test/features/clone-type-create-duplicate/sdk/structures/IUser.ts
  test/features/clone-type-create-duplicate/src/test/features/test.ts
  test/features/clone-type-create-duplicate/swagger.json
Labels: bug

#1027 Bump up dependencies of `@nestia/migrate`.
  packages/migrate/.gitignore
  packages/migrate/package-lock.json
  packages/migrate/package.json
  packages/migrate/src/MigrateApplication.ts
  packages/migrate/src/analyzers/MigrateAnalyzer.ts
  packages/migrate/src/analyzers/MigrateControllerAnalyzer.ts
  packages/migrate/src/archivers/MigrateFileArchiver.ts
  packages/migrate/src/executable/bundle.ts
  packages/migrate/src/module.ts
  packages/migrate/src/programmers/MigrateApiFileProgrammer.ts
  packages/migrate/src/programmers/MigrateApiFunctionProgrammer.ts
  packages/migrate/src/programmers/MigrateApiNamespaceProgrammer.ts
  packages/migrate/src/programmers/MigrateApiProgrammer.ts
  packages/migrate/src/programmers/MigrateApiSimulatationProgrammer.ts
  packages/migrate/src/programmers/MigrateApiStartProgrammer.ts
  packages/migrate/src/programmers/MigrateE2eFileProgrammer.ts
  packages/migrate/src/programmers/MigrateE2eProgrammer.ts
  packages/migrate/src/programmers/MigrateNestControllerProgrammer.ts
  packages/migrate/src/programmers/MigrateNestMethodProgrammer.ts
  packages/migrate/src/programmers/MigrateNestModuleProgrammer.ts
  packages/migrate/src/programmers/MigrateNestProgrammer.ts
  packages/migrate/src/structures/IHttpMigrateController.ts
  packages/migrate/src/structures/IHttpMigrateDto.ts
  packages/migrate/src/structures/IHttpMigrateFile.ts
  packages/migrate/src/structures/IHttpMigrateProgram.ts
  packages/migrate/src/structures/IHttpMigrateRoute.ts
  packages/migrate/src/structures/IHttpMigrateSchema.ts
  packages/migrate/src/structures/IMigrateController.ts
  packages/migrate/src/structures/IMigrateRoute.ts
  packages/migrate/src/structures/IMigrateSchema.ts
  packages/migrate/src/test/index.ts
  website/package.json
Labels: enhancement

#1033 Fix #1018: add `FormDataInput<T>` type for React Native environment.
  package.json
  packages/core/package.json
  packages/fetcher/package.json
  packages/fetcher/src/FormDataInput.ts
  packages/fetcher/src/index.ts
  packages/fetcher/src/internal/FetcherBase.ts
  packages/migrate/package.json
  packages/sdk/package.json
  packages/sdk/src/generates/internal/SdkAliasCollection.ts
  test/features/multipart-form-data-fastify/src/api/functional/multipart/index.ts
  test/features/multipart-form-data-fastify/swagger.json
  test/features/multipart-form-data/src/api/functional/multipart/index.ts
  test/features/multipart-form-data/swagger.json
  test/package.json
  website/package.json
Labels: bug, enhancement

#1035 Publish new `@nestia/migrate`
  packages/migrate/package-lock.json
  packages/migrate/package.json
  website/package.json
Labels: enhancement

#1041 Add `@` symbol breaker on `@nestia/migrate`
  packages/migrate/package-lock.json
  packages/migrate/package.json
  packages/migrate/src/internal/MigrateCommander.ts
  packages/migrate/src/test/index.ts
  packages/migrate/src/utils/StringUtil.ts
  website/package.json
Labels: bug, enhancement

#1049 Close #1046: support ``@ApiProduces()` decorator of `@nestjs/swagger`
  benchmark/package.json
  package.json
  packages/core/package.json
  packages/fetcher/package.json
  packages/sdk/package.json
  packages/sdk/src/analyses/ReflectHttpOperationResponseAnalyzer.ts
  test/features/plain/src/controllers/PlainController.ts
  test/features/plain/src/test/features/api/test_api_plain_template.ts
  test/features/plain/swagger.json
  test/package.json
Labels: enhancement

#1055 Close #1054: add support for ApiExtension decorator
  packages/core/package.json
  packages/sdk/package.json
  packages/sdk/src/analyses/ReflectHttpOperationAnalyzer.ts
  packages/sdk/src/analyses/ReflectMetadataAnalyzer.ts
  packages/sdk/src/analyses/TypedHttpRouteAnalyzer.ts
  packages/sdk/src/generates/internal/SwaggerOperationComposer.ts
  packages/sdk/src/structures/IReflectHttpOperation.ts
  packages/sdk/src/structures/ITypedHttpRoute.ts
  test/features/swagger-customizer/swagger.json
  test/features/swagger-example/swagger.json
  test/features/swagger-extensions/nestia.config.ts
  test/features/swagger-extensions/package.json
  test/features/swagger-extensions/src/api/HttpError.ts
  test/features/swagger-extensions/src/api/IConnection.ts
  test/features/swagger-extensions/src/api/Primitive.ts
  test/features/swagger-extensions/src/api/Resolved.ts
  test/features/swagger-extensions/src/api/functional/health/index.ts
  test/features/swagger-extensions/src/api/functional/index.ts
  test/features/swagger-extensions/src/api/functional/performance/index.ts
  test/features/swagger-extensions/src/api/index.ts
  test/features/swagger-extensions/src/api/module.ts
  test/features/swagger-extensions/src/api/structures/IPerformance.ts
  test/features/swagger-extensions/src/api/structures/ISystem.ts
  test/features/swagger-extensions/src/controllers/HealthController.ts
  test/features/swagger-extensions/src/controllers/PerformanceController.ts
  test/features/swagger-extensions/src/test/features/api/automated/test_api_health_get.ts
  test/features/swagger-extensions/src/test/features/api/automated/test_api_performance_get.ts
  test/features/swagger-extensions/src/test/features/swagger/test_swagger.ts
  test/features/swagger-extensions/src/test/index.ts
  test/features/swagger-extensions/swagger.json
  test/features/swagger-extensions/tsconfig.json
  test/package.json
  website/pages/docs/sdk/swagger.mdx
Labels: enhancement, good first issue
