Repository samchon/nestia, pull requests merged in 2024-01, with the labels that each got.

#745 Fix `EncryptedModule` error when internal `imports` exists.
  benchmark/package.json
  build/index.js
  deploy/index.js
  deploy/publish.js
  package.json
  packages/core/package.json
  packages/core/src/decorators/EncryptedModule.ts
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/sdk/package.json
  test/executable/start.js
  test/features/all/swagger.json
  test/features/app-globalPrefix-versionUri-routerModule/swagger.json
  test/features/app-globalPrefix-versionUri/swagger.json
  test/features/app-globalPrefix/swagger.json
  test/features/app-routerModule/swagger.json
  test/features/app-versionHeader/swagger.json
  test/features/app-versionUri/swagger.json
  test/features/app/swagger.json
  test/features/beautify-4/swagger.json
  test/features/beautify-false/swagger.json
  test/features/beautify/swagger.json
  test/features/body-config-assert/swagger.json
  test/features/body/swagger.json
  test/features/distribute-assert/packages/api/package.json
  test/features/distribute-json/packages/api/package.json
  test/features/distribute/packages/api/package.json
  test/features/encrypted/nestia.config.ts
  test/features/encrypted/src/Backend.ts
  test/features/encrypted/src/api/functional/performance/index.ts
  test/features/encrypted/src/controllers/MyModule.ts
  test/features/encrypted/src/controllers/monitors/HealthController.ts
  test/features/encrypted/src/controllers/monitors/MonitorModule.ts
  test/features/encrypted/src/controllers/monitors/PerformanceController.ts
  test/features/encrypted/src/controllers/sellers/SellerAuthenticateController.ts
  test/features/encrypted/src/controllers/sellers/SellerModule.ts
  test/features/encrypted/swagger.json
  test/package.json
  website/pages/docs/sdk/sdk.mdx
Labels: bug

#749 Enhance `TestValidator.sort()` function.
  packages/e2e/package.json
  packages/e2e/src/TestValidator.ts
  packages/e2e/src/test/features/test_validate_sort.ts
Labels: enhancement

#758 Fix #757 - Swagger Controller file path error
  packages/sdk/src/analyses/ConfigAnalyzer.ts
  test/features/swagger-한글경로/nestia.config.ts
  test/features/swagger-한글경로/package.json
  test/features/swagger-한글경로/src/api/HttpError.ts
  test/features/swagger-한글경로/src/api/IConnection.ts
  test/features/swagger-한글경로/src/api/Primitive.ts
  test/features/swagger-한글경로/src/api/functional/health/index.ts
  test/features/swagger-한글경로/src/api/functional/index.ts
  test/features/swagger-한글경로/src/api/functional/performance/index.ts
  test/features/swagger-한글경로/src/api/index.ts
  test/features/swagger-한글경로/src/api/module.ts
  test/features/swagger-한글경로/src/api/structures/IPerformance.ts
  test/features/swagger-한글경로/src/api/structures/ISystem.ts
  test/features/swagger-한글경로/src/app.module.ts
  test/features/swagger-한글경로/src/controllers/HealthController.ts
  test/features/swagger-한글경로/src/controllers/PerformanceController.ts
  test/features/swagger-한글경로/src/test/features/api/automated/test_api_health_get.ts
  test/features/swagger-한글경로/src/test/features/api/automated/test_api_performance_get.ts
  test/features/swagger-한글경로/src/test/features/swagger/test_swagger.ts
  test/features/swagger-한글경로/src/test/index.ts
  test/features/swagger-한글경로/swagger.json
  test/features/swagger-한글경로/tsconfig.json
Labels: enhancement, good first issue

#767 Complement #764 - `pnpm` in `@nestia/migrate`
  packages/migrate/package.json
Labels: bug, enhancement
