Repository samchon/nestia, pull requests merged in 2024-04, with the labels that each got.

#857 Erase ISwaggerComponents["x-nestia-namespace"] property.
  packages/migrate/package.json
  packages/migrate/src/programmers/MigrateSchemaProgrammer.ts
  packages/migrate/src/structures/ISwaggerComponents.ts
  website/package.json
Labels: enhancement

#860 Adapt `typia`s `JsonSchemaPlugin` tag in `@nestia/editor` .
  packages/migrate/assets/input/bbs.json
  packages/migrate/package.json
  packages/migrate/src/factories/TypeLiteralFactory.ts
  packages/migrate/src/programmers/MigrateImportProgrammer.ts
  packages/migrate/src/programmers/MigrateSchemaProgrammer.ts
  packages/migrate/src/structures/ISwaggerSchema.ts
  website/package.json
Labels: enhancement

#858 Support swagger tag description
  package.json
  packages/core/package.json
  packages/fetcher/package.json
  packages/sdk/package.json
  packages/sdk/src/INestiaConfig.ts
  packages/sdk/src/generates/SwaggerGenerator.ts
  packages/sdk/src/structures/ISwagger.ts
  packages/sdk/src/structures/ISwaggerServer.ts
  packages/sdk/src/structures/ISwaggerTag.ts
  test/features/tags/nestia.config.ts
  test/features/tags/src/api/functional/bbs/articles/index.ts
  test/features/tags/src/controllers/BbsArticlesController.ts
  test/features/tags/swagger.json
  test/package.json
  website/pages/docs/sdk/swagger.mdx
Labels: enhancement

#861 `TestValidator.equals()` to trace more detaily.
  packages/e2e/package.json
  packages/e2e/src/TestValidator.ts
Labels: enhancement

#869 Enhance `@nestia/migrate` for invalid path parameterized.
  .github/dependabot.yml
  benchmark/package.json
  package.json
  packages/core/package.json
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/migrate/src/analyzers/MigrateMethodAnalyzer.ts
  packages/migrate/src/internal/MigrateCommander.ts
  packages/sdk/package.json
  test/package.json
  website/package.json
  website/pages/docs/sdk/sdk.mdx
Labels: enhancement

#870 Now `@nestia/editor` supports every OpenAPI versions.
  packages/migrate/package.json
  website/package.json
  website/pages/docs/editor.mdx
Labels: documentation, enhancement

#871 Upgrade `@samchon/openapi` and adapt its memoization rule.
  package.json
  packages/core/package.json
  packages/fetcher/package.json
  packages/migrate/assets/input/v3.1/bbs31.json
  packages/migrate/assets/input/v3.1/iamport31.json
  packages/migrate/assets/input/v3.1/shopping31.json
  packages/migrate/assets/input/v3.1/toss31.json
  packages/migrate/package.json
  packages/migrate/src/MigrateApplication.ts
  packages/sdk/package.json
  packages/sdk/src/generates/SwaggerGenerator.ts
  test/package.json
  website/package.json
  website/pages/docs/editor.mdx
  website/pages/docs/migrate.mdx
  website/src/constants/EDITOR_EXAMPLES.ts
Labels: enhancement

#873 Patch bug of samchon/typia#1029
  benchmark/package.json
  package.json
  packages/core/package.json
  packages/e2e/package.json
  packages/fetcher/package.json
  packages/migrate/package.json
  packages/migrate/src/analyzers/MigrateMethodAnalyzer.ts
  packages/sdk/package.json
  test/package.json
  website/package.json
Labels: enhancement

#874 Upgrade `@samchon/openapi` for its bug reason
  packages/migrate/package.json
  website/package.json
Labels: bug, enhancement

#876 Update swagger.mdx with OpenAPI v3.1 content.
  test/features/swagger-customizer/src/decorators/SelectorParam.ts
  test/features/swagger-customizer/swagger.json
  test/features/tags/nestia.config.ts
  test/features/tags/src/controllers/BbsArticlesController.ts
  test/features/tags/swagger.json
  website/pages/docs/sdk/swagger.mdx
Labels: documentation

#878 Fix broken `website/pages/docs/sdk/sdk.mdx`
  website/package.json
  website/pages/docs/sdk/sdk.mdx
Labels: bug, documentation

#881 Support `anyOf` and `webhook` types in the `@nestia/migrate`
  packages/migrate/assets/input/v3.1/webhook.json
  packages/migrate/package.json
  packages/migrate/src/analyzers/MigrateControllerAnalyzer.ts
  website/package.json
Labels: enhancement

#884 Close #715: `@WebSocketRoute()` decorators.
  packages/core/package.json
  packages/core/src/adaptors/WebSocketAdaptor.ts
  packages/core/src/decorators/TypedQuery.ts
  packages/core/src/decorators/WebSocketRoute.ts
  packages/core/src/decorators/internal/IWebSocketRouteReflect.ts
  packages/core/src/decorators/internal/validate_request_body.ts
  packages/core/src/decorators/internal/validate_request_form_data.ts
  packages/core/src/decorators/internal/validate_request_headers.ts
  packages/core/src/decorators/internal/validate_request_query.ts
  packages/core/src/module.ts
  packages/core/src/transformers/ParameterDecoratorTransformer.ts
  packages/core/src/typings/get-function-location.d.ts
  packages/core/src/utils/ArrayUtil.ts
Labels: enhancement
